export const myLinks = {
  links: [
    { label: "Sint Maarten", href: "http://ozkir.sg/lozapuw" },
    { label: "Azerbaijan", href: "http://cuinuk.iq/jiwwocaw" },
    { label: "Bulgaria", href: "http://jerepa.cu/opzisak" },
    { label: "Yemen", href: "http://vufodewu.pm/jiclenko" },
    { label: "Madagascar", href: "http://ezoc.mh/ilco" },
    { label: "Dominica", href: "http://jeh.tl/nicti" },
    { label: "Jamaica", href: "http://gahtude.sg/co" },
    { label: "Laos", href: "http://agehodima.co/cacoop" },
    { label: "Latvia", href: "http://uvodaewa.rs/nekaz" },
    { label: "Niue", href: "http://bisovoseg.ug/focasar" },
    { label: "Japan", href: "http://mog.pr/pu" },
    { label: "Faroe Islands", href: "http://vaspopben.jp/weani" },
    { label: "Moldova", href: "http://gif.uk/te" },
    { label: "Northern Mariana Islands", href: "http://usze.pn/va" },
    { label: "Mexico", href: "http://pirde.gq/ala" },
    { label: "Puerto Rico", href: "http://lu.tp/jafesi" },
    { label: "Papua New Guinea", href: "http://linehiru.lb/mif" },
    { label: "Lebanon", href: "http://abziloh.ne/zugo" },
    { label: "Caribbean Netherlands", href: "http://ka.li/juug" },
    { label: "Turkmenistan", href: "http://par.mm/pive" },
    { label: "Somalia", href: "http://boremi.cd/dozoguij" },
    { label: "Malawi", href: "http://tekacmu.ba/buh" },
    { label: "Andorra", href: "http://zorualu.ph/su" },
    { label: "St. Martin", href: "http://uwiime.bh/zaorsi" },
    { label: "Saudi Arabia", href: "http://pitiz.tc/jiw" },
    { label: "Tunisia", href: "http://wahob.iq/rapdupni" },
    { label: "Nicaragua", href: "http://se.bv/hit" },
    { label: "Lithuania", href: "http://zirwaroz.qa/gobesre" },
    { label: "Mali", href: "http://huf.lr/lotnis" },
    { label: "Tuvalu", href: "http://najibe.ws/tudiul" },
    { label: "Israel", href: "http://enuabaos.gb/gem" },
    { label: "Tuvalu", href: "http://gigu.sa/duc" },
    { label: "Canary Islands", href: "http://zeh.tm/obu" },
    { label: "Cayman Islands", href: "http://mu.za/lu" },
    { label: "Lesotho", href: "http://ga.hu/nif" },
    { label: "Turks & Caicos Islands", href: "http://burwiko.dj/kuucosu" },
    { label: "Guyana", href: "http://macecwi.jp/hojub" },
    { label: "Chile", href: "http://deba.co.uk/fazsevi" },
    { label: "Argentina", href: "http://mav.jp/retuhos" },
    { label: "Fiji", href: "http://boh.kp/eszulo" },
    { label: "Comoros", href: "http://vig.sx/kapuc" },
    { label: "United Kingdom", href: "http://ud.th/cefbopi" },
    { label: "Tonga", href: "http://owtorzus.tl/ofner" },
    { label: "Samoa", href: "http://cewamfe.in/ki" },
    { label: "Algeria", href: "http://pil.io/bofvuguz" },
    { label: "Guyana", href: "http://maitdes.kg/ba" },
    { label: "Colombia", href: "http://puho.gp/wevagog" },
    { label: "Brazil", href: "http://suw.tn/mibof" },
    { label: "Tajikistan", href: "http://idzaf.la/fi" },
    { label: "Mexico", href: "http://muhwawnam.tg/ik" },
    { label: "Pakistan", href: "http://zoginegi.tv/hic" },
    { label: "Tajikistan", href: "http://up.co.uk/puwuesi" },
    { label: "Mongolia", href: "http://siw.na/nibsi" },
    { label: "Finland", href: "http://ipenu.zw/oj" },
    { label: "Seychelles", href: "http://sa.lc/poz" },
    { label: "Marshall Islands", href: "http://sagta.hr/lekjik" },
    { label: "Croatia", href: "http://nicap.ba/bighoc" },
    { label: "Faroe Islands", href: "http://fapam.mx/naw" },
    { label: "Hong Kong SAR China", href: "http://okfafsav.ru/evafokkop" },
    { label: "Nicaragua", href: "http://nahuc.ci/sen" },
    { label: "South Sudan", href: "http://mavunem.aw/vapvo" },
    { label: "Benin", href: "http://gejim.pg/pah" },
    { label: "Brazil", href: "http://bejcanji.com/afehep" },
    { label: "Jamaica", href: "http://fittutnof.be/mad" },
    { label: "China", href: "http://bu.ls/fengeseh" },
    { label: "Venezuela", href: "http://zodeji.pr/bosjekeh" },
    { label: "American Samoa", href: "http://lavut.ni/isatotup" },
    { label: "French Guiana", href: "http://wif.pw/zeni" },
    { label: "Cape Verde", href: "http://sudwe.is/usa" },
    { label: "Belgium", href: "http://bep.mu/su" },
    { label: "Mali", href: "http://gupizcir.sk/gol" },
    { label: "Lesotho", href: "http://eba.ug/negab" },
    { label: "U.S. Outlying Islands", href: "http://woj.org/vi" },
    { label: "Puerto Rico", href: "http://eru.wf/dubelo" },
    { label: "Cocos (Keeling) Islands", href: "http://oni.cn/ejomovu" },
    { label: "Bulgaria", href: "http://ajbi.jm/deccinez" },
    { label: "Mongolia", href: "http://gewekafot.gs/wupam" },
    { label: "Uruguay", href: "http://egojo.ps/huhge" },
    { label: "Slovenia", href: "http://dunme.fr/ebe" },
    { label: "Turkey", href: "http://ka.gd/jeshe" },
    { label: "Zambia", href: "http://ecipesa.pa/mo" },
    { label: "Marshall Islands", href: "http://zo.pg/hiamosa" },
    { label: "St. Martin", href: "http://ro.tw/fop" },
    { label: "Cocos (Keeling) Islands", href: "http://irwe.hk/bambabo" },
    { label: "Canada", href: "http://sisuwan.bv/oca" },
    { label: "Mali", href: "http://ifunehe.gq/hube" },
    { label: "Latvia", href: "http://wiseb.bz/pavi" },
    { label: "Sint Maarten", href: "http://vu.mh/aluhi" },
    { label: "Saudi Arabia", href: "http://ireleuki.edu/me" },
    { label: "St. Martin", href: "http://seba.sa/viitgif" },
  ]

};